# Generated by Django 2.1.1 on 2018-09-20 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Hostal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=150)),
                ('latitud', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True)),
                ('telefono1', models.CharField(blank=True, max_length=12, null=True)),
                ('telefono2', models.CharField(blank=True, max_length=12, null=True)),
                ('precio_minimo', models.IntegerField(default=0)),
                ('precio_maximo', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='motelnow.Departamento')),
            ],
        ),
    ]
